# Generated by Django 5.0.6 on 2024-09-28 14:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core_root", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="member",
            name="firstname",
        ),
        migrations.RemoveField(
            model_name="member",
            name="lastname",
        ),
        migrations.AddField(
            model_name="member",
            name="email",
            field=models.EmailField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="member",
            name="first_name",
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name="member",
            name="last_name",
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
